apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech
  template:
    metadata:
      labels:
        app: tech
    spec:
      containers:
        - name: tech
          image: tugy/tech:sha-b4c33ac
          ports:
            - containerPort: 3000
          env:
            - name: DB_PATH
              value: /data/tech.db
            - name: WEBHOOK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tech-webhook-token
                  key: token
          volumeMounts:
            - name: db
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: tech-db
