---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tech-webhook-token
  namespace: apps
spec:
  encryptedData:
    token: AgAyPMs4mmQV4qxTMLHiLgyu13xqG4deOrZLNIfG/cw3NkSt6ZJ9pW364Hq2+ItkvgrdmdPq6yp/ExcpX1IAMwskmQwbBQ1wLeVVzEJDRQwlOaj1EKDwBifZpNX+WcaEif0OPyzX6pRk3L3CTt/j552+mobKL5HL63G/h15AS8ZJIQz+HVDC2sYHwItYihoDf+/9bqu4gHg44B6ReNWJL0B0f8LnQ4NgVYpqCttn1uiRrkF5PofpBIqUr2bZuLA6OxE1aDH9i3Ym1bKyMy4pxtC3UcI4WcRdQGq4Oc9bvd/6XLPnO9gz9Zq1dalTNMbVjU5JI94K8bJ/rmnbsy8F/ruFxI0PKqD/4k4Fsc+0JZbWqcd8ml+/08LpQhNAvZ6ghlbiwMud8vSGIQS+AGvqqGJMhoNg5fFxpFEiDG97sKkGTkFn7omdDUZKTNrloxjvsuDxe+avxRX3cKrHPnQq5ZY/N3sMs/3CPp/yjK4au5tM3XrEh1wFzRz63b5TbDmP3ghWreQuEkiUcTIff59YYiA/yl1uJTxPsO83RxsW4iUb2pAiHO8nz0NzotOs4bsgW3aB+ydugzYLX2phO6dXz01mw0nt1NWOw8GrMrLomMYYD0nhit2YgBqOFFEb54jxIAn7wU0Ftjn352fttAthKsV0RtQY7FAVWC8LowrDxK7w+7j//h+WAk+RC3zdImPY1yaKC8JOO8QLm/ar105Wa9oNTy/ozyVotjj2tGbjHUnnUL4Yfl0nHgK9LGc2TBfPlkqBCZJ+L2LLRgFczsmX6cUf
  template:
    metadata:
      name: tech-webhook-token
      namespace: apps
