---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: infra
spec:
  encryptedData:
    token: AgCeVgXtDF1i1Hp/owH290gTgMQXMpIAq8+wwlPlOWa4IXQdjumt+RFldSRwEQlLeac8kdJU6uzglEkHZXkbBuqmUD7cg5fws+YvvDHD81z9L53XrmnIUBZu2AEH/nz6pzUK41DPNCl12cT58xd6HuoqJaH6oA4nq60A0MmTXxYAO7IggOLEbeaq+UP2I4UDQ6vedQyTwjlpPmKUKqJ6LxQCEko5u/jmBmW6fPoQ81ixfsYAdnUwyodr3mfTqybjANHXNxLmn+jWDeNBk2BGEO4ExGlTdA5QjKuKSKas6k5rJsC69VOSDsGAPHAUM1CvfQ5VlaI3sOCFH1CDsD9yhuG9Brlz2R0YgDL9Q/oW29ry7LPWZJk9Xb/UNum7P2LgIe0kzOdYVN9kOPVgOdqWFld3TwlZ+0SFYmjXcF9p6/gvx2GYeQ6eu739s27TfoDR/r7yALXT45jE3Sx3u78GxY3rU6OgUSoJBWuSWI5ZnJyLggY0Aqy3QyUkw90V1lR93ISqVnZYCAHIundVKGW+Cv7ruLsKRWslP+hZfufUgmDgQF36weiqsp8tdORweAkOwqBsLwKjdXQsAbN1P+fEKNknsamDPAJ7E8VYWGD2/tWJ1TG+dVegOZw34mtkfkkd7oBfYgP/BaOIBBk3QJoVyr+WCxWSMjgwW40FbXqIfcMgiEV3cCaGEF0Qbjj/iE0c3zr7t3SU2abQHzQFjz3CQ3Ot69H95xdzxGSzQ6dD3PHs/qUfqpm6rYpR+POadWOEMbnwp+/qwTtLfNehy4Giaie7yPKTq19Aqo81vMCozSrcDfM5qUGD89VPP09vIs/F0XElHfBf3b5MGV4OzZ+j0Np6T9FfAIahfKmIIAHE8lUsMrl3k4uR21G9pSWQK46hXofZzvPu6RbMXqZC8yCGalCM0fj2+nYjlq6VoIhlKkkhDHzJiy0=
  template:
    metadata:
      name: cloudflared-token
      namespace: infra
