---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-jwt-secret
  namespace: apps
spec:
  encryptedData:
    secret: AgBVLrs9GPZMjzU6or9eMZA1m+pQdyaFQtMlu+S9L7/i0oiAF8dfH6Suu3atQGT4gUZMCu9L2H+J/VqTSzbN9/mqsjgI2WpmTXkfzlS5ya3uzgTRD2kW4qzEZjN8AGKHMwjBxqNKGaTI6kK8lPXvCKPpfycYlW55uV+nvqOwxt0FRPvmhCwKz1WYfYNsk8Mn07Xl8PyCqRqYy+ahr3BHz4AvLg6LjhGYMjNtCoxBfc14tR7dBSaUxjXFUWpMGsTFV1mR5VN/dNZt5s1MQGDgGlHwg3N+gkyTdl4FzO07PR1rxV9CB12uyOx9aG1YcVGriWJUF0u+B9bqMl24fFkWlpKU6HkdKUOur0LoK1/tfU3VSr2T1hg3UEHMEDzsS0oR0bzOI0Jby5WUgf0bePrp8Y10Eo0UxdetBMhEj3ckVuL8zUuyajz9x2JdU/9Xs5Rilnwiu1XVyQ9ZxUUHFKk7UB67febj9lT696KKdu6JCPOj+3LxHg2Xk/CqbyVUjZPZM/Bz8Noyvx82aInT8Pd6ZSvdWFtyR/gGr76GcreKL/i980cacs7ik0HZJksWj1c8jAt9SWQ4Rvi78u4lLxqe72I0LTGwVuWmMkuwN3a8rUwDpqx3Bld9xpFsFy/bTWL+I003GT9NPMfMeHXIA6kL9Sctf5qFQE4V9ilavxRcJjyCH5oqT/7+EKJXHonUjNi0EI0OWqyt17iOyY/dsMe76UPxoC7fhKDUw7XGs1Tej+F5oNF8Zq0h7flL5b1Q
  template:
    metadata:
      name: mcp-jwt-secret
      namespace: apps
    type: Opaque
