---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-mcp-oauth
  namespace: apps
spec:
  encryptedData:
    clerkOAuthClientId: AgAXiIJfASk4ND2zbXqUAC7Zr+nm4b989ae3ahT5DsnocMgI7M+idQJR/9muLPloQGBjXMvCq+G8XKyB1Rzr+JyXCeX+kmcIs9NcOVA+luxNUIJ6k6p5o4tDQEJl/MXpCYyeB4sLrW5g+6pgAWxQXkHS+8ylFZDvJ6pp+7Ihx+ee16uau+Fc/MzVKs6Z5qaunOAT0sel1NsyGbe06BGZJXEZlA4Z1oEpeXcKKeSKV+JQjLz2uI7IgnMB7qq8OUQ/F9sl2hd/f4NLyfaZVBIYIONFnhNTR/MXbZ0UaaINT35feeWrrKZbIHqwkxMA6ymPGGd5obxnZOBpxx7y5NE2hvu31blVG6Qy6EqGFLuPdSTFHO2nGFewYx5nHQBrfck02vyUQYrB8C2dmedMwNEq/pnUk2bzhqEQPqes5fwH+HyXNrV3nfQiOOxiLCPvexEozcAPkK80+2YaGqTWRXJngm0SOFhxau6ZR1/OaMasUtWthsVsC46vSmpbyFWGUrgeaTZRk5OtN/w2M95/Fsa+FIOIT7fUrqylRywzoBDCHYw8rv2zzLS1ldFVLm20YtVh94Mnrb+TVl9OMD3N8a8R9VV1Pbs05zNJy1MxqSm4pZG+CSjrNNYn0KlTd8yalz8gR9zpUDwepZsZsiOFL7vugwmJV1E7GufuC9wxqGX3U1nOWQvjHv7EjzstgymB9/Jco3aHEOWH+8+Ptvk94hc8xTmA
    clerkOAuthClientSecret: AgA6rkrW58xPIEAi1/Edld05gVthALa16XJdiU2NXwGNkhXwDYSLHciHNLIj1LTc2qUNFPwyyDonSreHZMPXhk7CK1TYI5FGtVWI8Nide6Ug5l4/tFCI5GliCKhjg+3KD1YQl9IZOKh/P4kiHu+kl6/xvmS6JOZ7VdKhId8vKp/qlskwaUEkKImMHu71zH2GMhet8+3Wk9LC2MsxG4qGInR1U2tFSkXQqiQP0sBrz+9ZOcu9Tw8f3i46Qw6NDea3Pod562dSDp7rkiZ/k+ycEfc1ycIgLNsDJmz6wIOdsUDntsVwdWbp+MuEnxPpeIqDzL8SnVSRel7yhMWPOBJq4bebXKYVDEBXXdZGusfRXfu+gONGi4hehGFbLQs99GZ63KzWML/XJuvcwuBFmQxjOW+QPv9Uz5AgfwT7b0ig924avUqryYe+TH7kqlYnLA4TSKOm8ZmgBqsbe45TQVQHrADiVgtjLScHY2Ah4gXID/CPlq/ORVME3k4wd0Wg9ZxDGEcDTExRnetJdlT1KuyXyVog7ilzAgjJY00cGPlmlxNurkJ1AoBYNLz0xqYYK1z11wH7WpzHC55kM7Wq+dTNtJpsmQzGB6ON0DF+ycIbfka5m6EynjjeSRU46u6fxT2Qxo/CVp/K5W40rK9/g415Ryhgzp8A1ZkwJcBOSfNkiMOpWnND06XvWPM5o9sRqIIyivymy+ZSM47cpZ6vAd0KCvJb1LMiKL/A9/5pUquLCNMbGQ==
  template:
    metadata:
      name: recipes-mcp-oauth
      namespace: apps
    type: Opaque
