---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-mcp-oauth
  namespace: apps
spec:
  encryptedData:
    clerkOAuthClientId: AgANrA/CiVoU3KvYPeqXBYoyYV0Rh9YichZOk7ZIcd6Or1hedEbg4ZvWOLCjCn9RTVYeE8ZOSHrok7pXHERQkr4bM41pCkTnFI0KWupHYHP00xyn5lSOXxfhY7ayJDBuZMU5hwncCpU1U8ELyYtFsCw/+/MWs5edfhuqdgCWS07++03CNmDv2QAtHJzzCXVAH6Nys05vuAEt3LqkxEtm5Lwsgbm3wJJkZC3KCsygs+1qF9A2YOG+NJY9zxdd53MecqrKjhbEstwl4d9aR3UPhVyHcdaZjC5dQDVeieXH5V2Zd5jZiSrzap3YZBPUdJ1NMnY0QbRq7/GUraYVb2DLPflxAFHd7g2QE1fNPwpvejayJA7sXfJYIWGLR6IgqRs6a0o/0i6jzATbrn998zuydGEq6tYQ5sqVflHyLkG+d1k0G2ZzIzWh9KtQu/joJVjObM8M9IC4L5MCi1ULWVqQ3FTVmU3fmHPfJU7PxhwX7MEh5EDfdxx6KNOanL7wqxU1q7rqU2XHCf5kedJJ2oEMPlp9JDQ20iMMGRuhmv/rpmeE+0iSQ+g5Fh5Q91amIbqholE2COCUpUtK/gebZdn5LlJNeocq8C1ETOaFZnwnbq9t39xKGhI8TZjDpy9rzjDX1BXOAZf4H+1oyxHd9R4tWQqxRSoL5RVoKSRhWvJgX1T42iyNhxl9Uhe7QP7fedEaYzf1ZtAC5vmvT4JESvjMSgOf
    clerkOAuthClientSecret: AgA4JvydZZtSZECOGvHGLoEVUU/bK7z6VV8udi0rcv+Haj6tYHKWJdIya1F+xFUUoN/JB/TAw5s+OpngkXSY7YgAAt1i05st/cJ7yo6hxcOYD31APcroB4SGQGCi3tc+ePqhaRpbzr0O1LmX2Hhairf0isDRGinpPLXCmOkX10Jzzs+PVEkfkbMASXQKUR39mW1FQjjfYGOYhfKTUBO5j2roXWIVp3Di6XDIMr9stTYoVOPLu6yEMQY7ahxBjGum0TpxRn2P4wiqL5r9MWPyx2a07Ir85rTcfEWuWp3YRiC4v7EvudA8RQL6qKV/NmdG6OnLx4iTxDhqjLzLvKJPxPB3bBfa3XgebN/MtdJvf0tsuugQPxDqIMod58P6YvxkxbqHb1vqHXomDKgkq0j+D5lo20A9tDXBfyQ6vk+ENAt3ONwqvIsMMTQD1T3a2K2WrRzxmQpRGaeZH+EEqKrfv3YLckNo1tIffYEN0ily71cqgr5Zd+SClcCsv9n7n1a7jQKcoTQ1xRFxKWuxakX3dnp3FaJB6N9Kby6j1p7XgZu8aMF4LJwIJJswcgOdy2uuf9gJaj/gaJ9tkcnoGh8lA4jABWmrHfcsAUvgLTR+WnmMl+TiH0Ry8qeRTjs6y8SF9+LSlxeZzpGHqVUJXhdDg8FRBth8tq3ok9QW76ma8lYhrktWV49LiCLgh2MnziIdofmUzCsrkKugR3jSE0UevovBq4Xb2DMtFrTQhP94GSAEnw==
  template:
    metadata:
      name: recipes-mcp-oauth
      namespace: apps
    type: Opaque
