---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-mcp-apikey
  namespace: apps
spec:
  encryptedData:
    apiKey: AgBB+t0c9P9YcYQhc5Vhsnzl0tKMzGHW9r1eUL12BUdJEBWZ6j2hw6Gp46P55/NfK1O2B0PF4OM2roZEu+4W836s6vTLJ7MwXbuhNDC0mYaITuuRAHKxMtB2r8/vHOUhJ/cPEDXPJyClm79kwLH5xOK366VDBfD0rjkjAzUNBrVfO3C8Ubo1QYVmk7fVMm/WzlRxRGov0E4EI44X0upwEEVl+NEr8/XGkjlQqq5MGzNZhBdV+f55EacLPwYCTHfesyUH0goll/IAGenRZ4O+1jaFffx2m98AGbdg+W9qyW9WiYGYDOjsbLOz331zSjMtYF4e+OR1SdfsRyENSu78aBBnLO9f47liW3uPkqZMUJc45T9Q/yB1JaqEczcRGdqm7pAKB3zkcG7rR4o+CIwa++vnLeu8+V5Dh4+aNrvj5RuFs+Esjf8q0feajnmB69YgHd0FR7C2vTQrqkkSA9owDVQI+qmupOrpn0EmKSqgZh1uZPBVycIfASPYYNP62gdrw+VX1YRYSa7v99xUfnTCGyjcdavqmi1Lqa+lB3GibeGQ9gXoVwGCg9d8hL7OdRpFbqEeFImga6zQ60ZSJX+AUz/OkX8A0ypNP5m3ojIT89IBTD/MEH7KbilQSTjjg0UfI9Usql6XOrrc3x9DcLtB7Da0VLDg71dXaJBSzt5YrligR8UOuBke+SpXzX1u7zIcmk8oBaqatGdZak8Gh0JLG+eVFjbuKT9KVwWAuasbHN15kl2/Md+/tbl5CfvdK1SGU9c5Dj9s3vXEurnTW22E+GUh
  template:
    metadata:
      name: recipes-mcp-apikey
      namespace: apps
