---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adifinki-postgres-credentials
  namespace: adifinki
spec:
  encryptedData:
    database_url: AgBADL3CzmZckTbncWOcSrMdj5pcZJgyKR0apNbLqxWX6mhDAzveRFnlP+AET+m1y+bb6ea9zbyQ23KzWFWdlEqt+FARxDosr9MsmG3jcdzdiN/5tuoQz3HdKK6dEXgrUSxXgjNtgTLEFWdPSv/Eiym9UVs+d7dHuqd0zFs0040XTWej3pSBtRm/eKb/gz1+qP1UlN+dHXWrfnTnx+XFwgPIUf1zhGOu3n8dtC5Ghxh4yIhXWzZnm/7qD1lBJyBmHfzY+tXMdoFOxRSoBxZNQ2uYyOkITElYcNgLkt5bvCUTEFwpuz4+PQdnuUtyhqaRpV1set6NBcQ4GkHz7TWY7F4r3YOOAlxgYffqQMrUTksIveThUbIF7u1Z34Qf0h/AxYSqy5vhfpvRI0R/Kbwt6tqOyw0hU9gtdkDSSreUnpMpSZTnL5ZLfaxJj1eNDWiJlxSGNQjGnn5VhE3hvyFBkvf4+c9SwF2ZH3npDlv2Qhk2mVVVCVc+1g9s6KjZmlNNhNec8Ng8hqNZhiY6UJF8PBzT2fvRLF2+XfYGpCyc36CzgG0+mCLU6ilyTs11IP5Fa92hU71HEpS4Z57q7dKI+cV2FudAbeQ40JtRHCxJ9WS32JFu8poOdW9uRKxy2AZxcAyrM2xFcV6viyCxOBqMh9PHstcU2pIAF2j52SNmKw7ocdlGAwdHcV6io39yibUAyy+o3D6UOjMh4vk8GvOddbG2BIEc/zDGd2Hva7ax+EAc6JN6VbCWKKzPeiIJhuS7aPIxsRwXww5zEayS4bN4i6XuoBo90T09gSt2LQAwkShieTCyaLWIP69X7Xawcb/q6iz8HsTtOtRLCo0KxV81ZB7owVY=
  template:
    metadata:
      name: adifinki-postgres-credentials
      namespace: adifinki
