---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-api-gemini
  namespace: apps
spec:
  encryptedData:
    apiKey: AgBXl4sGifMCagjiLGttjyR8LL5VWSMPzn4dkanUgNqS5uXkD7AeVmjDwV6THJcVusMKiEbgBHhhhxnp/j3Clscv2Jg9hcCx78t3Ob9Job3quqpF5rfBcg6tfCMbjgjhHJp9rtx1qSpoGUbsdeh7hWOdJbUGsm7zqc3mhMYbiW2S/HGBARjTBygCxyFv6ofiQ6CztdeVDXwfK99NoyZqb+vHj8ibW/47c2H4fTmn/zyOQ4RsMVab2wXVkVi8Zu31WII47r0I1mD9l9SnKDNMVow/Hvw3a2aLgKC2gLp7LL8Uo9eunm34EHcZcFXqvW0Ae02L90DngJzftJKDA5GDZyfeE+o98PlKMeaMMdX47fsqZi1XAQ/LJ6waBSzpfYcFKPgoyZJkZPK67GcW7HDM5an/osEe13DCGsfXxxVlWXusePBlPt0mvXCPZMYuQVvSxrmq7PErJ/g8y+py/pyEYHc4TD2sFAszHBJdWpfp/TncZxboe8EI/vWZ4vHyZtIRBxPKI4B8aBN/quRX0IX0lZsnbpVvTEM6lIBtqOLVUBqpa/ViH4fSHhUcXuR2IQqI/0VuHNrxBCUEX11ASZFE0pEXz0gTj1YvyyE9TVV5RAxXGelOOiKjHuFsi1hXp7+Fb9aztY93Wj4miVMN0bXwk0xg82YjzZ286QEXANl+CYH+r1T8PP5XGCwoTviEzXqbc4KCN8d2ocYrE4LM6fokBBN/y2/LRg/Py6FEloKRm5yyujlh4iV8YVm/c3qISlZM+AzKOLBVjw==
  template:
    metadata:
      name: recipes-api-gemini
      namespace: apps
    type: Opaque
