---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-api-github
  namespace: apps
spec:
  encryptedData:
    token: AgC7F1SAByR0K6pw0X7e4g9Dnr5IwusXP6Zq55hDBK2JvrwFLxU2S4dbcCu3TaeB3eISFjlLulMwsKzMYgNocM9jqff1466lugWJawQV/jzlNghMfWVCtpt9JCpRhOapJ7EJwg2dBuDDjK/Bj9nLuqk4JUETzFUOpjqWl34K0BlqHAlt4mP1GDx68+kBlLzlImllm45MPSTom2zl867lD7BmnAM9j3Is46bPBqXHa5XCLM6HirmqLyn0CqwOf7ejKTSE/Rd+H1/1CUp5+IbSApMzvzN4NmYiEWkmQiUXClggc1gnAxW+KOmoNpLgqF0qAnd9EmtoOoRDeQ+4v/GK3EdPmv25GAGlKQWYDGjuzGjceiwrU/r3eCg98vnceLP6uHy/6yi7mgByregnbuJdiMGdjjRzhKdiJngF8jqt1O0UIqfyAH9f3d6zJS9u769ZV4ezsV8qC5dB4q1kWwRw5Jp1OnWdNueAVEwlKxkZVibvfIVjvacZANv9GZtoPyqMtylc3MLdK8dVB/vcaPH+9Pge/8/x0A5pBtme/SGd3r2pwIPT1sXeVATKXl1QgJnlg08Fm21A+f0IJ0Ruc42H4Pz7Krq6iGCzRnpjsZjK6/hY8yxKm5Fecf1AnVDhR5UGaD9ZY4+OsLNEV+5UGoMVFkW6Q1NUJgX13w2EikJQjMfbxgycIPBghQ2vn8zFtyHZZ1wzxIPPzyENwQT8cCppRDBdHX9JVvRzWb5u/Hh1ZR53tMUIrp5qSM7qwav+litnzWMzMN/PWbZgoTF0cjPrBlaubETuFiXpoZlt1LvGsOneTRCKfisqmS8Eibbj5Yw=
  template:
    metadata:
      name: recipes-api-github
      namespace: apps
