---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-api-clerk
  namespace: apps
spec:
  encryptedData:
    secretKey: AgAhZVyp6AGoAJuj1qS+Hop6a/xCnhGTm7H89XFVE/HdZTfzAuQQmYCNE1vaeGrugRf20MyaxtVSJ1Rwi2qAv5jz4c2Uj3qiY5NFw2fuOXUgLuymCOS6kvTo+huopnPYpnrOxoDU4mzriBk2NwrPCRyNOTyrI82GgQ/P5TIDaopxd+eBrO3a65MmuiwyQv4+yVEGwt7lOTi7MvXviNANFTQJgso7GuppC30YK4yChQJDGnre3wiWvqczEJTxV5n4U/NNDv8iDzaqGmBKKmzI6/HxPk+GJ3YaAxtqt37B8oWDTuhP9QqJUkQGJWc+fjGw9Ofy+/f7ADvYMm0WMIMCqc1SEvx9uDjpgGM9sc4KvT/B2NCyPqeqESR1FxPa62sxUvOs9VcSyLbFahFyXqI+FVBhIiCet9gnMLXddwSnPka8mx3iazFdiIk60yZj7rei7G73I8Ge+sHP2QV22ATVvGz0hUpARKuGInQ9znACAmoxiCkc2ynd1mCbH51mFeUyl/kyWYM1jOxQ5jwAslKAdMGIxqydTSNqbBzP0S6wrTTJbXGl7Gsn09rJg36l/on6Mts01YZzulSUhl8YyIlDW60p8vD6cl4O6lIA6gxK933Qd0kVi02tjW7ecxaDxJyZaRKxBrpx2SBGELmFfLsdKcdRdZLUOitqvA3KOA50V7KMSO3Y2NoeIWV+J5P27ZPEUHqhAv9wnY+bxJodpVyDR+7jkgs0yqaNHvOrtN2WtOl4W3OfwpSliEsMju/8HD01cCZyOw==
  template:
    metadata:
      name: recipes-api-clerk
      namespace: apps
