---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-api-clerk
  namespace: apps
spec:
  encryptedData:
    secretKey: AgChJRTWfm0B06MVVtgZOJLb4Bj3F29cfOcb8sgeRg74Wp+hglI82cPjofUGT9CPr/IWPxrywdwQw0j+gJQ9j9pD+uLik/fNZ6H9GNQ8aY904z7QaqXO0/GF2UCuSu1I3rUfIfuBQfgsMj1oiPEBMF16faugAhXcYa1CXw+jb6V59Fpm5zPmoDwmB56YwN5br7La5fwZMy09AmrhkAfUEwUrPfK4dhc+9ur0Q9xDGc4kGNjQwK0fMVA9cbCAOPATCW3fhhkO4JpxvlUFXKrEaqdzerE7KOm3Z36EFi5b5PIkf1TDf92vmzG+Rky8RgKlzQPjR0HRUGrRscwtSmtqe2BmNTOJ7KtU9e89jxY1dPmR1yhtting0ttlDsN2v8SQN8gXvOSaTZGZHBs/dSO2KahlewckJZwR1zmdOzNsdAEQpil/xFIwkKtgEvOOxw3G0pIgznJIKAnHYlRoIUjdsvALbyMDZnabz+z+6gl+WuAzzpk4K47QR/6BOKLcmVFjBdM7gAtBlyhln1+sG6vFZlzFBLWjT6F/I2c5sXqGqnP4qUOdr14TFr+t9eC7PrcPYrqa9cre8NTkOf/UzFnkV2I+rs+GgwnecHptNk9ky1FPgCX+NrOMs1oMqzZIXJn+spkWToHBupGZvC7UA4hKzZbnEull63XIqybD8lW3AYhMcWDeBRepgcaSYmLBIFkTOo4ToWRpZp2Jv4qsFrnQHV5rDk+FlpcW0eLcAh07WcSmoaYrlcYMROcz10sf1XEq7xv/tQ==
  template:
    metadata:
      name: recipes-api-clerk
      namespace: apps
    type: Opaque
