---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-api-clerk
  namespace: apps
spec:
  encryptedData:
    secretKey: AgABu9LEgMUPR/LIcSQt5Xn6ZoFrGUlS14sdx4cxbdY4uRClCAmCyWozwzCXHlDH/mm5RjsJwQA/uA6imk82pmhFwXSTq8l/pNwb6v1YzULjL54NjcXvAlIXeLrY9ANLY5mom8TBCiU7le1Y2yGTkt7Ng6hTGsnkgKBTxxhksANQoaaCqyunMFP4g/fTmBuRZaDqBla/C6OtFKZU4qKewmhDvtxbRwf29IX9IBsw/0nMg5p4VPdHq2rUofnOBhl3vtc79bdVFwgDi58sNCsD5j1TSyy8anBoKxQ0k+0Yx9yIcwF1DlJK5dGYofZ5ubGPhzVQZmYJBYtSagoJCYDbVjyT4UrIh+wSXJ3/oo5zXmT3fRAbglISphQWhNVzUsKFtSw4gieThPriKa6Pz+FNmlwmACUnlTmNqvC4EypYYIweBXr9pJ3IKryQMJ5XH+c5/WxVR+EmJH4p0vJqkLYxQOneF0/mxP/pONopaiciiMcC9g2IkYHqeTKOkDZnYtgcgCKNvfzS8fb9oF9SXm8MX5aSx6S8Sa8HAaCL2D6jiX2P1LzaVV3Mgvmhecbhjf4aXz0AmHLcO5Xf1203ziyj94oYNkwn79DYW+F45Zxi+sWFjyAVYwPsjo26qkzelvtreaBzbl28E07teu/8WIiSSMIZqc/PRArxv5DHmwlptrlTmZm9Azzh+fVVJtc7e2l/gahjzMkgq2sjRSJNMNpEWDNx/MKkhynE33NGeX0Fny9UhJMq/+/245rx56HXE44kp8bfGA==
  template:
    metadata:
      name: recipes-api-clerk
      namespace: apps
