---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-api-r2
  namespace: apps
spec:
  encryptedData:
    accessKeyId: AgC8L0J2vl74vVYHj5ECLGOe88R2w9G+0+ToJA/tH2+FPFvVz+xnjzHzBZBXihMDOmBdnhSi7skYn0lYl1fm1HphLslEapoMj9NYWG2VYcUVxhqDYGr9a4780iqhXBit/8GucnLhbq+tgiHHnpnA7OcVFjPa/7C7frpACAWziFLkJx9QynSXPeDgXa1dtnKGJbDAxOjF1oYCrazObWFLM4F2pk+ApifdfZxvDgQBblSsd6xvRMr7F1d2j5J/3YzR3LQxBonQ8+avUzMa7YCtiaJNpTJVL+r8bcV6CurhwhRp6KGBLfGxtsAAE2qCbb6X/JuLDaTkgDGRRQNVOsc8w7rterLHod+Tz4qPkc6lm3ZJXv99bC2gN0cLQQQ3brNy3pyj2qJSPzdvHhAN64KUwcWCXOD+n0OCWgTdlwq13kw6RdnH/uC0M2GTdq9VmzQuhA8UfZg0mR08BNjvdLtKwxAIcKT+h7+vKBYQbodcNK0HwK3GRPgosKas6zeGmQhctqZoNNRCopNU6KV8Zz5hbN3Zd7WFqxtsfqyrBKmGGx8Qzm7ozhJjZvVYjd+/eJl/F6JJcccJp5CbWoovABonzaHeCYOCWzyRZZNXMDzU+Na+JJCltkjTQzLrsamM5gIRbJ5APDbVRtTQCBAh3Q0Afxsqe3tCBMk6YAAoDEazIo7aX3TO0N11CZ05EMXRLuu+bDkbSlDf1Q/kKsYVBuOuPjvZNLnSo88L0La34m5rvxuXHA==
    secretAccessKey: AgCtfejVGjXeSd/6APCgt8JDI+TAU0ErYtZ+vJTsFiAMvu36xcVSWoAMSRjA8NhjpePJGNj0lpIdTe691Ay0jv8rhpIIqHCEsafpO+OuWMGESF0Ldducw6z1SY8E9T6RZ8eI8ZeSFroWroQJpSilgCZHwHjI8O9m4nPoMNqeyBAudaH2kWCLeoRw3wZ0YahgqQcl2puTN+B9h6RGHofFHj3bG5fBw3LY5IvYyvfkdavImH6tbNCDwGG19oFtythzPE+RyqVSWOUqkoooy6CuZXqT+CWL+qjlAnI6zfjQoTtYXa0IjP0CSGeVWuvjCzYXNBCDNr3++pFxr/UZmOxTcyAPi00Bv1xYuA46EH6kuZ/a7XHnN4VNBsfrv3zVoDE2e1i+rgtSffIszU2+s/Z7p9dKpibkLNrPdDlXOZXZorXvuSphDKd32vHlRo7mydhHdRCSLI/aXBjywiL7HFJeKl93RTZqA1bC143FGWf3dun3n1u612aRlz89DqDZwgwwY3Il1Hym6n8SG1vHksCRDMhArAKyzc3ySEwEYkF35AsXWQYNnkYljsd1vIRW/+q5lHliQ6KwStKsmNjAIIIbrSK+aOhh03NgvQLollFNDDEgM7eUoagMmsDun0m9l+cT3qnWHYO7OAx//XcaP8fyIagvW8QOgIlyEK642U2KKmvSOvXz8A/ryzazo7WpPOHzg2NOZzD/eSfTORsyiBeU6FveyeR6ZrLs+IXGRRoxvbatKLoPgoTqWfJEDrRfl6yAlEJgTOAWNYaSYLyCHrqFI46C
  template:
    metadata:
      name: recipes-api-r2
      namespace: apps
