---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: recipes-api-mongo
  namespace: apps
spec:
  encryptedData:
    uri: AgCM8GOddvsO50O1y8MiQlKlgR0femxuSLMKLijzu2+E4zJ5TsrgRYdc09gpeHKzWCJu+PPH1cOs11hSCc1VFnUO42LJiGEN9CBkVC0Mk7anloZscqvPXctLCnfWmxQPRZWPMjl5pI2tF5NSX+N0VWTwnrXpiwvCPHFXMwo7ZKwd154KgFZDaqPtKE3tCZ/UmdJM1tiZCSLbZKBAcWmF72t17uBlkjKLnmTx8wkwFv5QddGd+w7C6Vxp4TsnBz1qGAc2EHODyvpdckm9M/SF/5apCCMs4Fg8RU5yFst4xzwgE5YMyof317hbY58QedYGOWlHD1O+uUELqICPw/4xRygZkmf7lQjktIyhdHIDP3i7+KuA635xkDHGXGu0qcgL6yP1M4+F4cknNy5H2dWt5i1uNZ22lpzCoarnayTsemV+bh06ba3w+OLKJLrTixwDhW1pvzDH9D61dIoUMBn10/eKklIomxdCoVQMbC5NN0nTmgjdl/6maMEiLR6hCBrnAff51tUn97kuEMQwb8I2CAlNLrDI/+a0V6A0m/LyDanAyS2JwCnrlqa9DLepWssL/FLywuiMi9d8DiRgviMiVxwu+kRmrnEzgovYUc0e6ftxbsMg8Xg1e7U1zM/rt5dPsVUhbCy8CkPerm+csPY68gHcK6W9d7Nk1sL4KZ0JitjEfauq3QegLF+b550AbL3U7iERUzMLjgZelb4Y90YbfrAJgdf8b51rHCLVx/2VY9GW8deXUePQ4eqdtuMBJ/kOYHRiYuPex6paovADRVf7PbEOfQuWcjXvuZxpDdx3Z9FpZUW34LuC+a78UT+axDUhJtLejr9cBy6FngYuI4PyoB5tTf8=
  template:
    metadata:
      name: recipes-api-mongo
      namespace: apps
