---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-credentials
  namespace: apps
spec:
  encryptedData:
    email: AgBaOLn1aZrlZXXstqBZ/fBvOxQ45RW5pDbAVGGVAPJRDUV4v/vVe5OjKgPYsj5P8nlekNpAXLvgOfzmtlJj1ASem3WMMukCq16wlOBW3HJ9YqIUhnOHaRnyQQPeU4Qy5nI7KmogcpYqNpZiIsjaHEtwIzTOrVOcdU0BZyMMFHuuSrSDoHsCdp01ruajGV7fbTsx78Ed8HudUZghEP1X2oX10F44xz/PMPNo7FbGZiJTcF3PrSZ5dzzI14Oj4PhQ32o9sBq3kxvdtKvPdQFafqp2aocuUMlBbXcAsFC2qp6ptrGxpqy9NY03JlwJx8aHJztA6xC3ACcU1IKMvPixZOeC9fCbCpUUhdQqCG5QtFoZFQBJePFjFdMLCqmCWk/LWj5Xmmz8Tu5A9c3e24eDFvv2f/q4MnBSCnKUaDEBvwfoYcwk7NWFGCT3fbGjgfapIWvJshFGudvMBTHB0Y8bxt9DzvpO0eOVYpkOm6ypL2klFpw4X3S26wnyGz2bieXmWMs9MnlcXjgADpjARZMBnlf9MTfDF3uAqsQnxbhhtP+Jn3X/z1lvhxyAG0/+BHDWZr6G0MOzeJty8NDmsghFZY133FCI8/DM1eG4Wdk+UZzwVAuwz6Zgxu8GI/CNcT5QembUIrByJ4YamEmVrQMi6j/JXnLfQDztig5xAqajjXnluAr4O3cV99Armzp6eUsocpEzb6QDxiO4KEKQrEq22g==
    password: AgA2PUp65BmTDKlfOuknHtobFPOMFfy7x8H4F2CKe/822NXr27c5BlivAxZ7TYQxwcY5Yn07n/PMy12+2APIBKrBaD4dMDPONcd/a0ZToAcuq4Y/GHFeGMMZbogMb8/Z5toxMQztBP8g6S1np86H/LbCCdVglS9GXqPosbZkp5g9/qzLpXRGPKJFJuGQi2aeCPFjp/37g1hAmdBTSK6ir8786RC2AfUalDRIQSUi/5uMMUKH+75hhjEnWKRNa47rezGNbg4sFybwoKQ1ux0iH0jE5vFflQgbw1fNNwLLuWh5Lp0+z6mQZNvFxDXgiHrY4e7DemhQGcJTWnNgKitqP8GmBkHozlz6oWiUPlt6F6u89g6sCgCkJ5j2UQNSAadYBpH847oNsT9G5y6J0iQHVKkN5APyrNneBH/SiyvrkBVSo77nRwbh3GjWFwiH+bKRYV6nblWAr49sNRato6PZwdeoj8hmCq1+q1ZlDNS7ggE40Lv/6PLPR/XrVsJCImMeWGXIn9G+DWmvNFAfuMb17oNnnw9c/XWejZp4D5IjAm/R5YSdSNKGVFO/eJDhQARce/ZZ46SC8SOLePLcoNiVMO6Rf+tCGGYHoNfHYBPxezDLFNBoXzoih/OacCTWXkreWGgNVZd9MyJZTTLCFSusw1lNKITf7BUoGQFeCx5h4KfkVoGw3E/0TgMvb+t35W5zLJsLXTrba4uuWJWDfKNa2E/qawGAy8CBkPnN4TIcPXw=
  template:
    metadata:
      name: pgadmin-credentials
      namespace: apps
