---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: apps
spec:
  encryptedData:
    password: AgBfXpYbZ5PRt0xAhYqdOhNzS0P1e/C/MRzCrOvH0qr6xN6gXgrGJ9t2BQISNf0XcIvT1bjcDJjLVunKYlX7mopFGaPClfIzV5hBQ4oYdCUPVL2NxbiXDjcuZ/9wjkoYuL3cYRw4vxiexi0oh5s2yWZUkbP8PxsNWG7f+JamrWdN0EEIVGbClOnacwWbg+KEFy/SwYfuJQnHu6v4QQjRc7DZ+w28tHCwoJ1eSgS9wvhp37W2SB+jMLicRh0Lhk9LE+Z73HLRGPISyDFhevP+EFaUY0OUScKys/6sii45x6LaE9B005sm8Netst3kOvjXC3pw8c/xIr8jcAhuERUWitwmbNt1RatFfPGYy3n2dmmrO33pLt00GfixhPHDCirG48g0s1s4E8GDonzzI0MmR8Nug5JCuEPGucZw+SbCltgaAl4gl9vT5QMIw27EMPicQT98kjfZ/ByKN45wPDVcjDEZKBop9/0jPgXSEOByV5znbKA4C8zK0nVd1TVTH1jxguUP6SPJ5CRTvez+qac2ykvJUSf1KGuh/vuje5XPqyTZniXYL88rRO5Wl4YFR4rAsM7n3Ahw7mxU2QamAjW79xTj5SXyLeDq8tNcxvkBLjXkGJ00l/9nfHEim84oZiw+JOeeThKGsTvFcoyiMQkDaA48Fu4bV9xR3va3lORDbPGhlaOpkk47ajvS0ffqQuF3GoNeb33oygXk7dSe9cJX+7crYc8dtxiARjQnCYB95RB6eg==
    username: AgCF5g/DPzrs/qPu8qQ2agnePPM9zO5vh5+rkuZXoexMQH3nVuwDmyuvKrD2JJncvr6sq8pRVvjyQD/9zNu7nZIe5ZDjg/xfOMHcbKQvrUdaKZln31d8q8qy/72++1GNXS6Ic6+E+LhSLZUsrxdYI5OF6MbKDc8mrRfLiOVdvf7qY+B8RKJ+MeB7qEw0l74+4gNcrBtSh3BMQskFnqOZcb73F+EyphbElz2QSl1+vruIsfXvJsRFxOX18NdmTNtxcE+OnVzoCqmp33EoZjBuFI/y+JaZqUn4BFXd06fl7VJ2Xo9hgojPA411PD7lr2PXNqPnv/Bp/48i8CjlcfsXkNy3KNVzWP/+4cNEa3VV+as8TerGctWkASMcCuqhPhFQ9mNIagTs8a6uOROvK2Jmh/QgKjVWnajZy3MBfsmvBmJNSt7qPXE7LTg2eO1zCSMvlzbZIe9iiEwJgdBX6hnoZEAoiZriRtcWiJq6qy5asp4LqLlqejlPOuc8ptLonIgZibe07RWjem13VCPdXHBN85KqP6+ks01a8+MOm5/OI36B8VRX4YpX4f4xKTpqNNw0oLy+E322HTZ5uo5tRGChWg2xi7Mb+VfF4tzjWxqWwKedMuO1lwISNN0cQa39Q2ry0xMST34rOedhhNxpoJmbcnLyR2HzGzK5mwFoS1Guo8IMNsalwA4m2oaPRuAnuj6E/UCGjnG521oWxw==
  template:
    metadata:
      name: postgresql-credentials
      namespace: apps
