apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: adifinki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: tugy/adifinki-portfolio:sha-b57565c
          ports:
            - containerPort: 8002
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: MARKET_DATA_URL
              value: http://market-data:8001
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: adifinki-postgres-credentials
                  key: database_url
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
