---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-admin
  namespace: apps
spec:
  encryptedData:
    password: AgC+fQU1S3R8VW4suqlp+PnGMgWPUThna2B/b/Co3Iqhbjc3/+jdXUqTeieUaNjGy/vMrBKaUS1QZjliSdeU7oCb3lBWjUeRfwIHX+XXT8MgV/eeRYZWkKJ1JdA21jFaAg1iu3qEw64MlaRlEVjgCK9SRpanZNAswXcl9kKbx5sxwiShNjGqtFZdXkrhQpEx4S2zjIHw+ttW9Q1YXR3Y/iApoCMM/FhakjlZ5Tt2edak5NZI3loenSbfgogx8nrZIiZANHmNsCrTXMoyOP1QaaJSVmt77wIZP3f8o5/cY5Gei3KLzk4CxYZ/3c4nSg8J9X15CLdRbZZYZl9Q4MHB4j/fHZYJN848Qv+uRhHs6MURMJ8yLOBNRmBpWWoK1J4mfetdgfDob1RcbQ8Zxo34sXQhTnlN3Xk6pFjg0qqA19eOlIY59V5+M5LCnTdW7knavl+kVqzqdzz+LQKUqKKTprBY4FdfvQg5CzBkaUr5h3yZGycUB9bOfcv8FqbMn0Pp25rYGpO7jWSknyg52tMEd2rp9g5UJOa3siTJFtzMr6eeB3jNFHUFnhbvOOhH+WFZGk1py4m4+mLJMlEniwu1C9pZwqGrRWrnjOdhe7XyEWdWZnDWFBs1F9h94LiDflMNGfnJ8R2HSpnyUv4ddoidRePuZWqYYNETnT65KitFUkx8epvJud5lj4hhB8Yt+p6aMnrF3PHnTl0FD2P5xOquHoQBWu0NdRjWp0hVL2YHUU8QNA==
    username: AgB5r6RADkkKPpZ8zuTpvQt+0mEAc/yjpQfjg9lVKexkPIhxdRuiS6uNA5vxcEhzEgqF5ChE2D844OJXYNI6yA7kt2igrBCK8ub0qIChryCb00PjoudNq31bc14cjtCLne8DZX7jccmIQmm3gGoeWLJNBRKBzbdyr80uQhIC3A30XvSJz2MeP83t4XoDwQHZ1dLz5Wz9TjOXb3v3XkEJKb8WVDnHQ2iv+Oxv+k1buT0bhKiDPTQK1yTL9izHU9D3vtcNEWtUm1Aoshu0AwZksEB3L0twV7C5rOyJUrfoCwva1UhDunue2DxMyYxs4JmJK3158RWxwwvt3uJYKX5hQ7Nskp51Nzb4E2klc9O9zOT5l73CWOJ2d8JKCsb7vZzrhUvDDztr7Qiicol6v8Tppd2ugSETlFWHeaCrJi+gmCb3SJqdwgX9V6l0Qvi39loew4WLMH/PG1rxpYqjlhYEWqcLpHn6n5HxF5OFaA1Drfcjsz8KRojuHIphcrbOkc0Q9wLmvel9zSL015Lu1zo/YFV3yRADFyS2QknUXgV1wnL6sI2fbiJnS32fjaItAERmalHB/0NW/jzogznFNOUR2Rx8ZMSwMAFrB1JmxjVRfRsr+hNhVyCjV6bMI0iX7ruplmVkkuLTwmRkDG1Oh+opYfEhM9GkJMG/JAgG++fdt7KDEYz4DD9RUVtpwZ0m2JeO3BHIkoK8Yw==
  template:
    metadata:
      name: mongo-admin
      namespace: apps
